/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComplaintFormRouteImport } from './routes/complaintForm'
import { Route as IndexRouteImport } from './routes/index'

const ComplaintFormRoute = ComplaintFormRouteImport.update({
  id: '/complaintForm',
  path: '/complaintForm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaintForm': typeof ComplaintFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaintForm': typeof ComplaintFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaintForm': typeof ComplaintFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/complaintForm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complaintForm'
  id: '__root__' | '/' | '/complaintForm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintFormRoute: typeof ComplaintFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complaintForm': {
      id: '/complaintForm'
      path: '/complaintForm'
      fullPath: '/complaintForm'
      preLoaderRoute: typeof ComplaintFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintFormRoute: ComplaintFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
